# Generated by Django 2.1 on 2018-11-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_auto_20181121_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ('name',), 'verbose_name': 'stream', 'verbose_name_plural': 'streams'},
        ),
    ]
