# Generated by Django 2.1 on 2018-11-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_auto_20181123_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='total_rating',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='total_rating_count',
        ),
    ]
