# Generated by Django 2.1 on 2018-10-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181013_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
